version: "3.8"

services:
  mongodb:
    image: mongodb:latest
    container_name: mongodb
    environment:
      MONGODB_DB: mongodb
      MONGODB_USER: nesttest
      MONGODB_PASSWORD: nesttest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/mongodb/data
    networks:
      - nestjs

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb+srv://nesttest:nesttest@nesttest.exnjfgz.mongodb.net/Nesttest?retryWrites=true&w=majority&appName=Nesttest # Sesuaikan dengan kredensial dan nama database yang sesuai
    networks:
      - nestjs

networks:
  nestjs:
    driver: bridge

volumes:
  pg_data: