version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nestjs

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://local:local@postgres:5432/postgres?schema=public # Sesuaikan dengan kredensial dan nama database yang sesuai
    networks:
      - nestjs

networks:
  nestjs:
    driver: bridge

volumes:
  pg_data: