version: '3'
services:
  api-auth:
    build:
      context: ./api-auth
    ports:
      - '3000:4000'
    depends_on:
      - auth-services

  api-profile:
    build:
      context: ./api_profile
    ports:
      - '3012:4000'
    depends_on:
      - auth-services
      - Profile-services

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8000:4000'
    depends_on:
      - app-services


    
   