version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
