version: '3'
services:
  api-auth:
    build:
      context: ./api-auth
    ports:
      - '3000:3000'
    environment:
      - SVC_DB_PROFILE=http://api-profile:3012
  
  api-profile:
    build:
      context: ./api-profile
    ports:
      - '3012:3012'
    depends_on:
      -  api-auth
    environment:
      - SVC_DB_AUTH=http://api-auth:3000

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8000:8000'
    depends_on:
      - api-profile
    environment:
      - SVC_DB_AUTH=http://api-auth:3000
      - SVC_DB_PROFILE=http://api-profile:3012
    
   