version: '3'
services:
  api-auth:
    build:
      context: ./api-auth
    ports:
      - '3000:4000'
    depends_on:
      - rabbitmq

  api-profile:
    build:
      context: ./api_profile
    ports:
      - '3012:4000'
    depends_on:
      - account-services
      - profile-services

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '8000:4000'
    depends_on:
      - rabbitmq

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    
   